let items=JSON.parse(localStorage.getItem("callawayGalleryV4")||"null")||JSON.parse(JSON.stringify(window.CALLAWAY_GALLERY||[]));let uploaded="";
const labels={leadership:"Leadership",service:"Service",drill:"Drill & Color Guard",adventure:"Adventure",academics:"Academics",events:"Events"};
const save=()=>localStorage.setItem("callawayGalleryV4",JSON.stringify(items));
function toast(m){const t=document.getElementById("toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
document.getElementById("fileInput").onchange=e=>{const f=e.target.files[0];if(!f)return;document.getElementById("fileName").textContent=f.name;const r=new FileReader();r.onload=()=>{uploaded=r.result;toast("Photo ready")};r.readAsDataURL(f)};
document.getElementById("addBtn").onclick=()=>{const image=uploaded||document.getElementById("urlInput").value.trim(),title=document.getElementById("titleInput").value.trim();if(!image)return toast("Choose a photo or URL");if(!title)return toast("Enter a title");items.push({image,title,caption:document.getElementById("captionInput").value.trim(),category:document.getElementById("categoryInput").value,layout:document.getElementById("layoutInput").value});save();render();toast("Photo added");uploaded="";document.getElementById("fileInput").value="";document.getElementById("fileName").textContent="No photo selected";document.getElementById("urlInput").value="";document.getElementById("titleInput").value="";document.getElementById("captionInput").value=""};
function render(){const c=document.getElementById("cards");c.innerHTML="";document.getElementById("count").textContent=items.length;items.forEach((p,i)=>{const d=document.createElement("div");d.className="card";d.innerHTML=`<img src="${p.image}"><div class="body"><span>${labels[p.category]||p.category} • ${p.layout}</span><h3>${p.title}</h3><p>${p.caption||""}</p><div class="buttons"><button>↑</button><button>↓</button><button>EDIT</button><button>DELETE</button></div></div>`;const b=d.querySelectorAll("button");b[0].onclick=()=>{if(i>0){[items[i-1],items[i]]=[items[i],items[i-1]];save();render()}};b[1].onclick=()=>{if(i<items.length-1){[items[i+1],items[i]]=[items[i],items[i+1]];save();render()}};b[2].onclick=()=>{let t=prompt("Title:",p.title);if(t!==null)p.title=t||p.title;let cap=prompt("Caption:",p.caption||"");if(cap!==null)p.caption=cap;save();render()};b[3].onclick=()=>{if(confirm("Delete this photo?")){items.splice(i,1);save();render()}};c.appendChild(d)})}
document.getElementById("resetBtn").onclick=()=>{if(confirm("Reset manager to the original sample gallery?")){items=JSON.parse(JSON.stringify(window.CALLAWAY_GALLERY||[]));save();render()}};
document.getElementById("exportBtn").onclick=()=>{const text="window.CALLAWAY_GALLERY = "+JSON.stringify(items,null,2)+";";const blob=new Blob([text],{type:"text/javascript"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="gallery-data.js";a.click();URL.revokeObjectURL(url);toast("gallery-data.js exported")};
render();